AWSTemplateFormatVersion: '2010-09-09'
Description: Infraestructura para despliegue de app Vite React en S3

Parameters:
  BuildArtifactUrl:
    Type: String
    Description: URL del artefacto build.zip en S3

Resources:
  StaticSiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StaticSiteBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub '${StaticSiteBucket.Arn}/*'

Outputs:
  WebsiteURL:
    Description: 'URL del sitio web'
    Value: !GetAtt StaticSiteBucket.WebsiteURL
